version: '3'

services:
    cron:
        build:
            context: .
            dockerfile: cron_Dockerfile
        image: jwansek/power
        env_file:
            - ./power.env
        restart: always
