version: "3"

services:
    mqtt:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./.passwords://mosquitto/passwd_file
            - mosquitto-data:/mosquitto/data
            - mosquitto-logs:/mosquitto/log

volumes:
    mosquitto-data:
    mosquitto-logs:
