global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: pushgateway
   static_configs:
    - targets:
       - pushgateway:9091
 - job_name: mqtt
   static_configs:
    - targets:
       - mqtt_client:8000

